export const bridge: string
export const bridgeButton: string
export const bridgeCard: string
export const bridgeCardCol: string
export const bridgeCardLabel: string
export const bridgeCardLabelName: string
export const bridgeCardLabelValue: string
export const bridgeCardNetwork: string
export const bridgeCardNetworks: string
export const bridgeCardNetworkValue: string
export const bridgeInput: string
export const bridgeInputContainer: string
export const bridgeInputError: string
export const bridgeTitle: string
export const errorMessage: string
