export const addOn: string
export const balance: string
export const button: string
export const buttonStake: string
export const cardShadow: string
export const checkbox: string
export const imgIcon: string
export const inputValue: string
export const stakeAdderCard: string
export const stakeHeader: string
export const stakeType: string
export const tokenCheck: string
export const tokenidList: string
export const tokenLabel: string
