export const apy: string
export const btn: string
export const button: string
export const infoIcon: string
export const linkImg: string
export const loader: string
export const loading: string
export const percent: string
export const spin: string
export const stackCardsChild: string
export const stakeButton: string
export const stakeButtons: string
export const stakeCards: string
export const staked: string
export const stakeDetails: string
export const stakeEarned: string
export const stakeName: string
export const stakeNftContainer: string
export const stakeNftDesc: string
export const stakeNftMint: string
export const stakeNftTitle: string
export const stakeNftView: string
export const stakes: string
export const stakeTitle: string
export const stakeValue: string
export const stakeValueDisabled: string
export const stakeValues: string
export const stakeValueTitle: string
export const transactionText: string
export const value: string
