export const aboutStake: string
export const aboutStakeCenter: string
export const activeClass: string
export const addOn: string
export const apy: string
export const balance: string
export const btn: string
export const burger: string
export const burgerIcon: string
export const button: string
export const buttonStake: string
export const cardContent: string
export const cardElement: string
export const cards: string
export const cardShadow: string
export const checkbox: string
export const connection: string
export const connectWallet: string
export const details: string
export const detailsConn: string
export const extended: string
export const imgIcon: string
export const infoIcon: string
export const inputValue: string
export const li: string
export const linkImg: string
export const loader: string
export const loading: string
export const logo: string
export const main: string
export const navbarMain: string
export const navbarName: string
export const navList: string
export const percent: string
export const sidebarMain: string
export const spin: string
export const stackCardsChild: string
export const stackingConnected: string
export const stakeAdderCard: string
export const stakeButton: string
export const stakeButtons: string
export const stakeCardList: string
export const stakeCards: string
export const stakeCardsList: string
export const staked: string
export const stakeDetails: string
export const stakeEarned: string
export const stakeHeader: string
export const stakeName: string
export const stakeNftContainer: string
export const stakeNftDesc: string
export const stakeNftMint: string
export const stakeNftTitle: string
export const stakeNftView: string
export const stakes: string
export const stakeTitle: string
export const stakeType: string
export const stakeValue: string
export const stakeValueDisabled: string
export const stakeValues: string
export const stakeValueTitle: string
export const tokenCheck: string
export const tokenidList: string
export const tokenLabel: string
export const transactionText: string
export const value: string
