export const card: string
export const cardArrowButton: string
export const cardArrowButtonActive: string
export const cardButton: string
export const cardFooter: string
export const cardHead: string
export const cardHeadLogo: string
export const cardInfoText: string
export const cardLabel: string
export const cardName: string
export const cardNameText: string
export const cardStakingConditions: string
export const cardStakingConditionsItem: string
export const cardStakingItemButtons: string
export const cardStakingItemDetails: string
export const cardStakingItemDetailsHide: string
export const cardStakingItemDetailsName: string
export const cardStakingItemDetailsRow: string
export const cardStakingItemDetailsValue: string
export const cardStakingItemHead: string
export const cardStakingItemInfo: string
export const cardStakingItemInfoBlock: string
export const cardStakingList: string
export const cardStakingListEmpty: string
export const cardTatalStakedValue: string
export const cardWrapper: string
export const errorMessage: string
export const hoverLoader: string
export const hoverLoaderTxHash: string
export const stakeModal: string
export const stakeModalBalance: string
export const stakeModalInput: string
export const stakeModalInputContainer: string
export const stakeModalMaxButton: string
export const stakeModalTitle: string
