export const closeMenuButton: string
export const sidebar: string
export const sidebarBackgroundLayer: string
export const sidebarBackgroundLayerHidden: string
export const sidebarHidden: string
export const sidebarLogo: string
export const sidebarNavItem: string
export const sidebarNavLink: string
export const sidebarNavLinkActive: string
export const sidebarNavLinkIcon: string
export const sidebarNavList: string
