export const accountAddress: string
export const accountAddressBlock: string
export const connectButton: string
export const connectionStatus: string
export const disconnectButton: string
export const networksMenu: string
export const networksMenuArrow: string
export const networksMenuButton: string
export const networksMenuHidden: string
export const networksMenuList: string
export const networksMenuWrapper: string
export const walletIcon: string
