export const card: string
export const cardButton: string
export const cardFooter: string
export const cardHead: string
export const cardHeadLogo: string
export const cardInfoText: string
export const cardLabel: string
export const cardName: string
export const cardNameText: string
export const cardStakingConditions: string
export const cardStakingConditionsItem: string
export const cardStakingItemButtons: string
export const cardStakingItemHead: string
export const cardStakingItemInfo: string
export const cardStakingItemInfoBlock: string
export const cardTatalStakedValue: string
export const cardWrapper: string
export const externalLink: string
export const externalLinkImg: string
export const stakeModal: string
